spring:
  jpa:
    database: MYSQL
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect.storage_engine: innodb
  datasource:
    hikari:
      maximum-pool-size: 4
  flyway:
    locations: classpath:invoice/flyway/{vendor}
    table: flyway_schema_history_invoice
    encoding: UTF-8
    baseline-on-migrate: true
    enabled: true
